DB_HOST: localhost
DB_NAME: hcf
DB_PORT: '3306'
DB_PASS: password
DB_USER: root

server_name: 'cheeky hcf'

kitmap_mode: false

enchant_limits:
  sharpness: 2
  protection: 2


server_claims:
  spawn:
    spawn_corner_1_x: null
    spawn_corner_1_z: null

  glowstone_mountain:
    claim_corner_1_x: null
    claim_corner_1_z: null
    claim_corner_2_x: null
    claim_corner_2_z: null

    # this is the area where the glowstone regenerates every 15 mins
    glowstone_respawn_area:
      corner_1_x: null
      corner_1_z: null
      corner_2_x: null
      corner_2_z: null


