name: hcfcore
version: '1.0-SNAPSHOT'
main: org.ayple.hcfcore.Hcfcore
api-version: '1.12.2'
authors: [Adam]
commands:
  faction:
    description: "core faction command"
    aliases: [f]
    usage: "/f [sub command]"

  logout:
    description: "logout safely"
    usage: "/logout"

  balance:
    description: "get your balance"
    usage: "/bal"
    aliases: [bal]